# certificate.yaml
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: firefly-test
  annotations:
    firefly.venafi.com/policy-name: "tiger-response Firefly Policy"
    # changed since I modularized the policy
    # firefly.venafi.com/policy-name: "Firefly Policy - tiger-response/firefly"
spec:
  commonName: jimmy.example.com
  issuerRef:
    name: firefly
    kind: Issuer
    group: firefly.venafi.com
  secretName: firefly-test-cert
